### ISSUE TITLE
Potential implementation to RetroArch - DosBox Pure (Xinput UWP ?)

### ISSUE THREAD

**Issue by Player1LoginXBOX** [memethyl/Mouse2Joystick#1]
Hi

After reviewing recent digital foundry video linked https://youtu.be/lrpkFuKh4CI 

Major complaint was mouse input is non existent on UWP apps and probably low priority bug for Microsoft.
I stumbled upon this and was curious if it could be tweaked for RetroArch & specifically DosBox Pure?

Converting C/C++ project to UWP it's not easy
And I see no alternatives in C#/.NET someone maybe already done that. Not sure. But since you could potentially just implement it into RetroArch possibly the code could be less intrusive and allow for RetroArch to read all mouse on UWP as an Xinput analog stick?

Thank you

**Comment by memethyl** [comment]
Microsoft seems to have made the arbitrary decision [to only allow mouse support for certain UWP titles.](https://docs.microsoft.com/en-us/answers/questions/505382/xbox-uwp-web-app-development-and-hardware-mouse-su.html) If RetroArch can't receive mouse input, neither can I.
In addition, [UWP apps are sandboxed,](https://stackoverflow.com/questions/57814391/global-low-level-mouse-hook-doesnt-get-called-when-uwp-desktop-app-is-out-of-fo) so I wouldn't be able to receive global mouse input anyway.

**Comment by danprice142** [comment]
Could any of this help with this issue? 

System Input Injection    
The inputInjectionBrokered restricted capability allows apps to inject various forms of input such as HID, touch, pen, keyboard or mouse into the system programmatically. This capability is typically used for collaboration apps that can take control of the system.

For a PC, input injection from an app that has this capability will only be received by processes in the same App Container.

<Capabilities><rescap:Capability Name="inputInjectionBrokered" /></Capabilities>

Observe Input   
The inputObservation restricted capability allows apps to observe various forms of raw input such as HID, touch, pen, keyboard, or mouse being received by the system regardless of its final destination.

This capability and the APIs related to it are only available for use by select Microsoft partners.

Suppress Input    
The inputSuppression restricted capability allows apps to suppress various forms of raw input such as HID, touch, pen, keyboard, or mouse from being received by the system.

This capability and the APIs related to it are only available for use by select Microsoft partners.
