### ISSUE TITLE
Application starts but has render bug

### ISSUE THREAD

**Issue by MemeGiver** [memethyl/Mouse2Joystick#2]
I have opened it as admin and non-admin but the issue dosent seem to fix

https://imgur.com/a/matFPWE

**Comment by memethyl** [comment]
What GPU do you have? M2J uses OpenGL 3.3, so if your GPU doesn't support that, then the window won't render correctly.

**Comment by MemeGiver** [comment]
> What GPU do you have? M2J uses OpenGL 3.3, so if your GPU doesn't support that, then the window won't render correctly.

Solved, Intel GPU dosent support OGL 3.3 but my dedicated one does after setting in the control panel
